# -*- coding: utf-8 -*-
"""Untitled62.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C4cnk_lGzZwDSFGrb2uIbe32sB91jZX4
"""

import streamlit as st
import pickle

# Load model and vectorizer
model = pickle.load(open("fake_news_model.pkl", "rb"))
vectorizer = pickle.load(open("vectorizer.pkl", "rb"))

st.title("📰 Fake News Detection App")
st.write("Enter a news article/text below and check whether it is Fake or Real.")

# Input box
user_input = st.text_area("Enter News Text Here:")

if st.button("Predict"):
    if user_input.strip() == "":
        st.warning("Please enter some text!")
    else:
        input_vector = vectorizer.transform([user_input])
        prediction = model.predict(input_vector)[0]

        if prediction == "Fake":
            st.error("❌ This News is FAKE")
        else:
            st.success("✅ This News is REAL")