# -*- coding: utf-8 -*-
"""Untitled57.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16TC5bu6YqF6zSfjGg9UhNhOKpnWjxej1
"""

pip install pandas scikit-learn streamlit

import pandas as pd
import pickle
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load dataset
df = pd.read_csv("Fake_Real_Data(in).csv", on_bad_lines='skip')

# Features and target
X = df["Text"]
y = df["label"]

# Convert text into numbers using TF-IDF
vectorizer = TfidfVectorizer(stop_words="english", max_df=0.7)
X_vectorized = vectorizer.fit_transform(X)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X_vectorized, y, test_size=0.2, random_state=42
)

# Train model
model = LogisticRegression()
model.fit(X_train, y_train)

# Predict accuracy
y_pred = model.predict(X_test)
print("Model Accuracy:", accuracy_score(y_test, y_pred))

# Save model and vectorizer
pickle.dump(model, open("fake_news_model.pkl", "wb"))
pickle.dump(vectorizer, open("vectorizer.pkl", "wb"))

print("Model and Vectorizer Saved Successfully!")

